# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

WORKDIR /app

# Copy only requirements and config files first for caching dependency installation
COPY pyproject.toml ./
COPY README.md ./

# Install dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir 'dotenv>=0.9.9' 'mcp[cli]>=1.5.0' 'requests>=2.32.3'

# Copy the rest of the application code
COPY . ./

# Expose any port if needed (MCP runs on stdio so not strictly necessary)

# Set the entrypoint to run the MCP server
ENTRYPOINT ["python", "server.py"]
